import Head from "next/head";
import Image from "next/image";
import Products from "../components/Products/Products";
import styles from "../styles/Home.module.sass";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planeta Doors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Products />
    </div>
  );
}
